### ISSUE TITLE
Doesn't allow search terms with spaces

### ISSUE THREAD

**Issue by Kircheneer** [Mikerah/WikiSummary#2]
The search term 'python (programming language)' for example doesn't work while just 'python' leads to a disambiguation page

**Comment by Mikerah** [comment]
It does allow search terms with spaces. However, one has to add double/single quotes around the search term. I guess that is just inconvenient, so I am currently fixing it.

**Comment by Kircheneer** [comment]
Are you entirely sure that works? Didn't work me iirc

**Comment by Mikerah** [comment]
Did you try it after I committed a new fix of after? Either case, I read that it may also depend on the shell one's using and how it interprets spaces in command line arguments. I'm on Windows and I usually use Powershell. But, it worked when I used the regular command prompt. So, I guess we'll have to make wiki summary more cross-platform
